import {
  Banknote,
  Briefcase,
  Car,
  CircleDollarSign,
  Clapperboard,
  Coffee,
  CreditCard,
  Gift,
  GraduationCap,
  HeartPulse,
  Home,
  Landmark,
  MoreHorizontal,
  PawPrint,
  PiggyBank,
  Plane,
  RotateCcw,
  Shield,
  Shirt,
  ShoppingBag,
  ShoppingCart,
  Smartphone,
  TrendingUp,
  UtensilsCrossed,
  Wallet,
  Wifi,
  Zap,
  type LucideIcon,
} from 'lucide-react'

export const ICONS: Record<string, LucideIcon> = {
  wallet: Wallet,
  banknote: Banknote,
  'piggy-bank': PiggyBank,
  'credit-card': CreditCard,
  landmark: Landmark,
  home: Home,
  zap: Zap,
  wifi: Wifi,
  'utensils-crossed': UtensilsCrossed,
  coffee: Coffee,
  car: Car,
  'heart-pulse': HeartPulse,
  'graduation-cap': GraduationCap,
  shield: Shield,
  'shopping-bag': ShoppingBag,
  'shopping-cart': ShoppingCart,
  shirt: Shirt,
  plane: Plane,
  'paw-print': PawPrint,
  gift: Gift,
  clapperboard: Clapperboard,
  briefcase: Briefcase,
  'trending-up': TrendingUp,
  'rotate-ccw': RotateCcw,
  'circle-dollar-sign': CircleDollarSign,
  smartphone: Smartphone,
  'more-horizontal': MoreHorizontal,
}

export const ICON_KEYS = Object.keys(ICONS)

export function getIcon(key: string | null | undefined): LucideIcon {
  return (key && ICONS[key]) || MoreHorizontal
}
